- id: forbid-secrets
  name: Check for unencrypted Kubernetes secrets in manifests
  description: "Forbid files containing unencrypted Kubernetes secrets to be commited"
  entry: forbid_secrets
  language: python
  files: ((^|/)*.(ya?ml)$)
